main: com.caiocinel.coordmarker.CoordMarker
name: CoordMarker
version: 1.1
author: okay
api-version: 1.21

commands:
  coords:
    description: "Open Coord Marker Main Menu."
    usage: "/coords"
  coords clear:
    description: "Delete all himself saved coordinates."
    usage: "/coords clear"
  coords create:
    description: "Create a new coordinate using provided parameters."
    usage: "/coords create <name> [<x> <y> <z>] [private = true] [<world>]"
  coords delete:
    description: "Delete saved coordinate with provided name."
    usage: "/coords delete <name>"
  coords item:
    description: "Change coordinate item with that's in hand."
    usage: "/coords item <name>"

  
permissions:
  coordmarker.admin:
    description: "Allow access to manage another player coordinates"
    default: op
    children:
      coordmarker.full: true


  coordmarker.full:
    description: "Allow use everything."
    default: op
    children:
      coordmarker.list: true
      coordmarker.clear: true
      coordmarker.create: true
      coordmarker.delete: true
      coordmarker.info: true
      coordmarker.changeitem: true
      coordmarker.rename: true
      coordmarker.createglobal: true
      coordmarker.teleport: true
      coordmarker.track: true
      coordmarker.preferences: true
      coordmarker.viewglobal: true
      coordmarker.privatemode: true


  coordmarker.list:
    description: "Allows players to view coordinate list."
    default: true

  coordmarker.clear:
    description: "Allows players to clear himself coordinates."
    default: true

  coordmarker.create:
    description: "Allows players to create new coordinates (private only)."
    default: true

  coordmarker.delete:
    description: "Allows players to delete a created coordinate."
    default: true

  coordmarker.info:
    description: "Allows players to view extended menu from created coordinates."
    default: true

  coordmarker.changeitem:
    description: "Allows players to change item used to display a created coordinates."
    default: true

  coordmarker.rename:
    description: "Allows players to rename created coordinates."
    default: true

  coordmarker.createglobal:
    description: "Allows players to create or set created coordinates as global."
    default: op

  coordmarker.teleport:
    description: "Allows players to teleport directly to coordinate."
    default: op

  coordmarker.track:
    description: "Allows players to track coordinates."
    default: true

  coordmarker.preferences:
    description: "Allows players to change main menu user-preferences."
    default: true

  coordmarker.viewglobal:
    description: "Allows players to view global coordinates."
    default: true

  coordmarker.privatemode:
    description: "Allows players to use private-mode."
    default: true



